spring.application.name=courses
spring.main.web-application-type=none
spring.ai.mcp.server.name=coursesmcp
spring.ai.mcp.server.version=0.0.1

# below must be disabled for the mcp server to work - to allow STDIO transport to work
spring.main.banner-mode=off
logging.pattern.console=